'''
Example TurtleMol Script
'''
import TurtleMol

iParams = {}
dParams = TurtleMol.defaultParams()

# Some very basic keywords, a full list has been provided below
iParams['shape'] = 'box'
iParams['numMolecules'] = 'fill'
iParams['structureFile'] = 'Your/Path/Here'
iParams['outputFile'] = 'Your/Path/Here'
iParams['sideLength'] = 4

# Updating the input parameters list using the default parameters to fill in gaps you didn't specify
for name in dParams:
    if name not in iParams:
        iParams[name] = dParams[name]

# Checks if you have a pre-existing structure defined
if iParams['baseStrucFile'] is not None:
    baseStruc, baseUnitCell = TurtleMol.readStrucFile(iParams['baseStrucFile'])
else:
    baseStruc = None

# Defines a unit cell variable that can store possible unit cell information
unitCell = None

# Reads the input structure file for your repeating tile
if isinstance(iParams['structureFile'], str):
    struc, unitCell = TurtleMol.readStrucFile(iParams['structureFile'])

# If the a unit cell is defined by your structure file, this loads it into the parameters
if unitCell:
    iParams['unitCell'] = [unitCell['a'], unitCell['b'], unitCell['c']]
    iParams['angle'] = [unitCell['alpha'], unitCell['beta'], unitCell['gamma']]

# Generates the structure based on the defined volume. Other functions for other volume shapes has been provided below
outStruc, strucType = TurtleMol.drawMolBox(struc, baseStruc, iParams)

# Writes an output file to your desired location
TurtleMol.writeOutput(outStruc, iParams['outputFile'], strucType)


'''
The Parameters
NOTE: Some parameters override each other. If you ar building a sphere, but define a sideLenght for instance, the sideLength term will be ignored.
      Make sure you define the correct parameters for each type of volume you want.
'''
dparams = {
'shape' : 'box', # (str): Other Options Inlcude: 'sphere', 'mesh', 'multimesh'
'sideLength' : 1.0, # (float): Only use if you want all sides of a box to be the same
'Xlen' : 1.0, # (float): Used to define the X dimension of a non-cuboid box
'Ylen' : 1.0, # (float): Used to define the Y dimension of a non-cuboid box
'Zlen' : 1.0, # (float): Used to define the Z dimension of a non-cuboid box
'sphereCenter' : [0, 0, 0], # (lst)
'radius' : 1.0, # Sets the radius of a spherical volume
'numMolecules' : 1, # (int): This can also be set to the string 'fill' if you want to pack as many tiles as other parameters allow
'tol' : 1.0, # (float): This is the minimum possible distance between any two tiles
'maxAttempts' : 10000, # (int): Used for randomly placing tiles, used to prevent infinite loops of attempting and failing tile palcement
'baseStrucCenter' : [0, 0, 0], # (lst)
'baseStrucFile' : None, # (str): A path to a pre-existing structure you want in the end result, but not one that is tiled
'randomizeOrient' : False, # (True/False): Randomly varies the orientation of the tile
'randFill' : False, # (True/False): Fills the volume randomly instead of in a grid-like fashion
'density' : None, # (float): Fills a volume based on density. This overrides othering filling options like numMolecules or tol. Units are in g/mL
'atomRadius' : 'AtomicRadius', # (str): Default uses the vdW radius, the CovalentRadius can also be used
'mesh' : None, # (str): A path to a .stl or .obj file for a volume defined by a mesh
'meshScale' : 1.0, # (float): Scales your mesh up or down in size
'scaleX' : None, # Currently not functioning properly
'scaleY' : None, # Currently not functioning properly
'scaleZ' : None, # Currently not functioning properly
'unitCell' : None, # (lst): Defines your unit cell parameters, is usually read in with the structure file
'angle' : [90, 90, 90], # (lst): Angles in your unit cell parameters, also read in with structure file
'hexagonal' : False, # True/False): A quick way to check hexagonal unit cell packing, rather than having TurtleMol determine the unit cell type
'globalMatrixPath' : None, # (str): Used for multimesh function. A path to a file that determines where meshes are in relation to each other, usually generated by Blender, SOLIDWORKS, ect.
'padding' : [0, 0, 0], # Currently not functioning properly
'onSurface' : False, # (True/False): Places the tiles on the nearest surface face of a mesh
'alignNormal' : False, # (True/False): Aligns the tiles with the nearest surface face normal of a mesh
'rotAngles' : [0, 0, 0], # (lst): Allows you to define a set rotation for your tile, rather than randomly rotating it
}

'''
Structure Generation Functions
NOTE: If you have the cellParams arguement, it must also be added into the writeOutput function as cellParams=cellParams
'''

# For a Box (No Unit Cell)
outStruc, strucType = TurtleMol.drawMolBox(struc, baseStruc, iParams)

# For a Box (Unit Cell)
outStruc, strucType, cellParams = TurtleMol.drawMolBox(struc, baseStruc, iParams)

# For a Sphere (No Unit Cell)
outStruc, strucType = TurtleMol.drawMolSphere(struc, baseStruc, iParams)

# For a Sphere (Unit Cell)
outStruc, strucType, cellParams = TurtleMol.drawMolSphere(struc, baseStruc, iParams)

# For a Mesh (No Unit Cell)
outStruc, strucType = TurtleMol.drawMolMesh(struc, baseStruc, iParams)

# For a Mesh (Unit Cell)
outStruc, strucType, cellParams = TurtleMol.drawMolMesh(struc, baseStruc, iParams)

# NOTE: For multiple meshes some more work may be needed on the script above. I have excluded it from this for simplicity
# but if you would like to use these functions, let me know and I will write a quick example

# For Multiple Meshs (No Unit Cell)
outStruc, strucType = TurtleMol.buildMultiMesh(struc, baseStruc, iParams)

# For Multiple Meshs (Unit Cell)
outStruc, strucType, cellParams = TurtleMol.buildMultiMesh(struc, baseStruc, iParams)