def defaultParams():
    '''
Keywords:
    shape = "Cube" or "Box" are the currently supported shapes
    sideLength = float(length of sides in a cube)
    Xlen = float(length of a box)
    Ylen = float(width of a box)
    Zlen = float(depth of a box)
    numMolecules = int(Number of molecules in box)
    tol = float(minimum distance between molecules)
    inputFile = Path to the input file if you are using one
    structureFile = Path to the structure file being used. 
        Required for usage. XYZ and PDB formats are currently supported
    outputFile = Path to output file if desired
    baseStrucFile = Path to file for a structure that is present, but
        not deuplicated
    baseStrucCenter = coordinates to place the geometric
        center of the base structure
    randomizeOrient = Boolean to randomize orientation of
        molecules
    randFill = When placing a set number of molecules, place them randomly
    desnity = total mass of molecules over the total volume
        of the system in g/mL
    atomRadius = Choose whether to use the AtomicRadius, CovalentRadius,
        or VanDerWaalsRadius

'''
    params = {
        'shape' : 'box', # (str): Other Options Inlcude: 'sphere', 'mesh', 'multimesh'
        'sideLength' : 1.0, # (float): Only use if you want all sides of a box to be the same
        'Xlen' : 1.0, # (float): Used to define the X dimension of a non-cuboid box
        'Ylen' : 1.0, # (float): Used to define the Y dimension of a non-cuboid box
        'Zlen' : 1.0, # (float): Used to define the Z dimension of a non-cuboid box
        'sphereCenter' : [0, 0, 0], # (lst)
        'radius' : 1.0, # Sets the radius of a spherical volume
        'numMolecules' : 1, # (int): This can also be set to the string 'fill' if you want to pack as many tiles as other parameters allow
        'tol' : 1.0, # (float): This is the minimum possible distance between any two tiles
        'maxAttempts' : 10000, # (int): Used for randomly placing tiles, used to prevent infinite loops of attempting and failing tile palcement
        'baseStrucCenter' : [0, 0, 0], # (lst)
        'baseStrucFile' : None, # (str): A path to a pre-existing structure you want in the end result, but not one that is tiled
        'randomizeOrient' : False, # (True/False): Randomly varies the orientation of the tile
        'randFill' : False, # (True/False): Fills the volume randomly instead of in a grid-like fashion
        'density' : None, # (float): Fills a volume based on density. This overrides othering filling options like numMolecules or tol. Units are in g/mL
        'atomRadius' : 'AtomicRadius', # (str): Default uses the vdW radius, the CovalentRadius can also be used
        'mesh' : None, # (str): A path to a .stl or .obj file for a volume defined by a mesh
        'meshScale' : 1.0, # (float): Scales your mesh up or down in size
        'scaleX' : None, # Currently not functioning properly
        'scaleY' : None, # Currently not functioning properly
        'scaleZ' : None, # Currently not functioning properly
        'unitCell' : None, # (lst): Defines your unit cell parameters, is usually read in with the structure file
        'angle' : [90, 90, 90], # (lst): Angles in your unit cell parameters, also read in with structure file
        'hexagonal' : False, # True/False): A quick way to check hexagonal unit cell packing, rather than having TurtleMol determine the unit cell type
        'globalMatrixPath' : None, # (str): Used for multimesh function. A path to a file that determines where meshes are in relation to each other, usually generated by Blender, SOLIDWORKS, ect.
        'padding' : [0, 0, 0], # Currently not functioning properly
        'onSurface' : False, # (True/False): Places the tiles on the nearest surface face of a mesh
        'alignNormal' : False, # (True/False): Aligns the tiles with the nearest surface face normal of a mesh
        'rotAngles' : [0, 0, 0], # (lst): Allows you to define a set rotation for your tile, rather than randomly rotating it
    }

    return params
